### ISSUE TITLE
XMRig proxy - mining pool profit switch

### ISSUE THREAD

**Issue by nerotulip90** [xmrig/xmrig-proxy#100]
Is there some script that will pull profitability data from some source like whattomine.com and then redirect proxy workers to the most profitable pool?

btw great job!

**Comment by MetallianFR68** [comment]
I managed to do that using PHP (QUICKPHP) and running a cron script that connects to whattomine (https://whattomine.com/coins/196.json), kills the XMRIG tasks (shell_exec + TASKKILL) and relaunch using a different config.json file (start xmrig.exe -c config_thiscrypto.json)

But whattomine has some erratic stats. They say since last week that SUMO is more profitable that ELECTRONEUM but this is far from true. cryptocoinsinfo.com is much better but i can't find any API. The only way is to calculate profitability yourself 👍 : your_hashrate * block_reward * (86400 / $block_time) / $network_hashrate * currency_value

Hope this helps

**Comment by nerotulip90** [comment]
Thanks for your answer. Does anybody know the most reliable website with network hashrate that support API calls?

**Comment by xmrig** [comment]
I recently found https://minecryptonight.net/ don't know anything about owner/stability, but data looks good, simple enough and has API.
Thank you.

**Comment by marki555** [comment]
But better would be if the proxy would support switching pool via API instead of restarting whole proxy (causing all miners to reconnect). The code to switch pools is already there (for failover), just enable its use via API.

**Comment by nutsnax** [comment]
I submitted a FR for a graceful shutdown/restart option. This issue is actually why I want it... but if there is some other mechanism to do this outside of killing the process and restarting that would be great also... kill two birds with one stone (the issue of miners losing work in the middle of coin change and the lost production when the proxy must shutdown and restart).

I was mostly concerned with the issue of cutting connections when miners are in the middle of work resulting in lost shares.

There might be one issue... and that is the handoff from coin to coin... if miners are submitting shares for SUMO and proxy switches to XMR ... how does the proxy know what to do with those SUMO shares?

**Comment by xmrig** [comment]
SUMO and XMR use same protocol and algorithm, it may change in future if Monero change PoW but now proxy and miner don't know what coin is used, only issue with AEON because of different algo, but same protocol. Once proxy connected to pool it receive job and broadcast it to miners, miners don't know it new job from same pool or from another.

* If hard restart proxy miners will loose time for reconnect to proxy, at least 5 seconds for xmrig miners with default settings.
* With soft restart without drop connections, loosing time will be equal to network latency for CPU miners and up to few seconds on top to GPU miners, because can't switch job immediately.

Please mind there no any middle of work exists.
Thank you.

**Comment by xmrig** [comment]
@marki555 In current dev branch now possible change pools via API, by change whole config https://github.com/xmrig/xmrig-proxy/issues/40#issuecomment-370202169 #119

**Comment by Andlar94** [comment]
@neurotulip90 I made a tool which auto generates a Config file for xmrig proxy based on profitability, if you're interested

**Comment by nerotulip90** [comment]
@Andlar94 Yes, I am interested.

**Comment by hiddenR88** [comment]
i am new to crypto mining, please need help on how i can start using xmrig for mining after a successful build.
