### ISSUE TITLE
can i use xmrig-proxy connect pool through xmrig-proxy?

### ISSUE THREAD

**Issue by crackwei** [xmrig/xmrig-proxy#118]
for now,i was bought some computing power from other person.and he use xmrig-proxy to manage his miner software.i want to link his xmrig-proxy to my xmirg-proxy.but there is a problem,it told me that "Invalid nonce; is miner not compatible with NiceHash?"

so my problem is can i connect a xmrig-proxy to other xmrig-proxy?if it's possible,how can i do?

**Comment by xmrig** [comment]
It not possible at this moment.
Theoretically it possible, but need proxy can work as simple TCP proxy (not reduce connection count), this mode not implemented.
Thank you.

**Comment by xmrig** [comment]
I added this issue to milestone v2.5 so very possible this feature will be added to version v2.5.
Thank you.

**Comment by crackwei** [comment]
that would be good,i think it's very useful for somebody who want to buy computing power.

**Comment by xmrig** [comment]
Added in commit https://github.com/xmrig/xmrig-proxy/commit/9efeb4a9b01c650b56421288137d4929893092f1

2 new options added:

* `mode` positive values: `nicehash` (default) and `simple`.
* `reuse-timeout` timeout in seconds, to reuse connections to pool, please note connection can't be reused immediately, only after new job received, this option can dramatically increase number of connections, disabled by default.

In `simple` mode, proxy can not reduce connection count, one miner will be equal to one connection to pool, be careful most pools don't like many connections.

Otherwise simple mode has some benefits:

* Possible make chain of proxies.
* Proxy can work with nicehash.com
* Nicehash support no required on miner side, until no other nicehash proxies in chain.

If you make chain of proxies, please note only one nicehash proxy possible in chain due technical reasons.

**Comment by crackwei** [comment]
good,thank you.

**Comment by DrStein99** [comment]
"Proxy can work with nicehash.com" - did I read this right?  Can I finally use xmrig with Nicehash now?!?!?  Does this still mean I can only attach 1 miner per-proxy per-nicehash connection, or will it finally allow me to combine my existing separate 20 miners I have under 600 h/s that can not do connect to Nicehash ?
