### ISSUE TITLE
The frequent occurrence of Stratum connection to IP interrupted

### ISSUE THREAD

**Issue by workboy** [xmrig/xmrig-proxy#140]
All machine frequent error hints: Stratum connection to IP interrupted
They are at the same time.
But I use Ping to check my network packet, and the connection between xmr-proxy and mine and my miner to xmr-proxy is normal. There is no loss of bag

**Comment by Spudz76** [comment]
Ping uses ICMP ECHO packets and does not show a TCP path.  It can be 100% and still TCP can be forcibly closed / filtered.
You are likely routed through some device (NAT or otherwise) with too-low TCP connection tracking timeouts / insufficient buffer space / intentionally forcing long connections closed (such as a 3G network? or other such policed Internet where long-polling and persistent TCP connections don't work).
You can try some other port that might not be filtered/mangled by your ISP or networking equipment.

**Comment by workboy** [comment]
Can you tell me which ports will be better, I'm using port 3333, thank you

**Comment by xmrig** [comment]
Proxy close connections after 10 minutes without activity, you can enable keealive or enable custom diff global or per miner. Don't forget you miner should support nicehash.
Thank you.
