### ISSUE TITLE
Supportxmr pool doesn't supported after PoW algo update

### ISSUE THREAD

**Issue by kostik2022** [xmrig/xmrig-proxy#163]
When trying to use, got message like: rejected (7/1) diff 10000 "Incorrect hashing protocol in use.  Please upgrade/fix your miner"

I use xmrig-cpu ver.2.5.2 and 2.6.1-b1, xmrig-proxy is v.2.5.2
The issue I  found with supportxmr pool.

**Comment by xmrig** [comment]
Any v2.5+ support new PoW without additional setup, but if you was change `variant` option to `0` your shares will be rejected.
Thank you.

**Comment by DrStein99** [comment]
I have been using the proxy w/ monero7 all day so far, no issues to report.

**Comment by JustHoldit** [comment]
kostik2022, I had the same problem today with supportxmr. It turns out I had a single miner that wasn't upgraded and it was causing my IP to be banned. If the porxy get benned all miners behind it get banned as well.. 

According to the admin at supportxmr the ban only lasts 5 minutes but I was banned for about an hour.

I ended up changing my proxy port and re-configuring all of my miners so I could weed out the bad one. It turns out it was some old box I was using for test/builds.

**Comment by xmrig** [comment]
Some miners behind proxy may not updated it can cause whole proxy banned by pool. `bad gateway` error mean proxy has no connection to pool. For me proxy works with supportxmr fine, was run 20 minutes test, no one share was rejected.
Thank you.

**Comment by chick0n** [comment]
OK...I looked at proxy log files. There are just 2.5.2 and 2.6.0b1 connected. It seems, only 2.6.0b1 produces "low difficulty share" errors.

Seems I have to go through my 2.6.0 machines again... Oh man... :)

**Comment by chick0n** [comment]
I updated all miners to 2.5.2. Everything runs smooth now. 0 Rejected Shares.

Looks like  xmrig-2.6.0-beta1-gcc-win64 produces crap shares on Windows 2012 Server Machines.

**Comment by JustHoldit** [comment]
I found a miner with an old version. My update script failed because the xmrig process was either hung or didn't shutdown fast enough.

If PoW is going to change every 6mo maybe there should be an optional line in proxy log that can report connected miner version. I know it would require an update to both proxy and xmrig but it should cut down on the bogus issues and make it much easier for us to manage our farms.
