### ISSUE TITLE
New Algo

### ISSUE THREAD

**Issue by goniboy** [xmrig/xmrig-proxy#166]
Now with recent changes we have Cryptonight-lite, Cryptonight, and Crytonight-heavy

Can be XMRIG-PROXY fixed to overid "algo" settings on xmrig clients.  For example now that turtlecoin is Cryptonight-lite, i must update all clients, and if i deside to mine another coin which doesnt use Cryptonight-lite algo, i must redo. Is there an opcion to overide mining client settings (regarding algo)

**Comment by nikkiman** [comment]
+1

**Comment by NicNull** [comment]
I really need this as well. As long as the clients can be opted in to accepting algo via protocol extensions from the proxy. So that a client connected directly to a public pool do not listen to incoming protocol changes by default.
Downside with swapping to other algo is the GPU specific changes that comes with this, i.e one setting is not optimal for same GPU card on different algos.
