### ISSUE TITLE
support for IPBC

### ISSUE THREAD

**Issue by eeeeLeeee** [xmrig/xmrig-proxy#179]
IPBC Have a own unique algorithm. Can you support for it?

**Comment by xmrig** [comment]
Use golden rule, don't mix incompatible algorithms in one proxy instance and it it will works.
Thank you.

**Comment by aleqx** [comment]
> Use golden rule, don't mix incompatible algorithms in one proxy instance and it it will works.

What do you mean? I doesn't work. I tried all combinations of algos and variants for xmrig-proxy and it doesn't work for the new IPBC algo (the miner is the xmr-stak fork at https://github.com/ipbc-dev/ipbc-miner)

**Comment by xmrig** [comment]
@ipbc-dev In your miner broken nicehash mode https://i.imgur.com/SeYbfQi.png last byte of nonce should be `7b` in this case. You remove question about nicehash from initial setup wizard, so I set `"use_nicehash" : true,` by hand and it did't help.
Thank you.

**Comment by xmrig** [comment]
Proxy support all cryptonight algorithms, until they not change stratum protocol, but if you miner not support IPBC proxy can't help. Also official IPBC miner can't work with this proxy, because they broke nicehash mode. I will support IPBC in miners, but it not high priority for me. IPBC team make just one single line change in algorithm, to break anything.

Official miner is badly forked xmr-stak, also they never submitted pull requests to upstream or open issues with details about changes. From my point of view anyone should avoid IPBC coin, they not professionals at least.

**Comment by xmrig** [comment]
@aleqx Get some fun form this comment https://github.com/xmrig/xmrig/issues/482#issuecomment-379134136 Don't worry I will support IPBC sometime later, maybe after a week, I just say it not high priority. It will be added together with #168

You exactly right we should work together, but most of coin authors refuse it. I think all parts in whole ecosystem is important.

**Comment by xmrig** [comment]
https://i.imgur.com/YdQyIUY.png very nice, official miner, official pool with over 85% of network.

**Comment by CryptoMinerd** [comment]
This smells fishy to me... **;-)**

- A "special" cryptonight IPBC ("heaviest") algorithm requiring their "special" miner fork to mine it
- A self hosted 49.57 of the total network 63.60 M/H = 78% making it much harder to score a new block for such a new coin (block height only 58029)
- A 1% Pool fee
- Double the memory requirements with slower hash rates than even SumoKoin's cyptonight heavy
- Current block reward is only 457 IPBC!

![exhibit1](https://user-images.githubusercontent.com/38143558/39076344-fd983fd0-44b7-11e8-886c-e9979e1edfcc.png)

**Upsides?**

- A little more ASIC resistance for the short term due to the fact that few devs have had the chance to release anything.
- Artificially inflated pricing
- More money for them

What does this really mean?

They have **little** community support! So why is their price still up? I call **cheating**!!!

![exhibit2](https://user-images.githubusercontent.com/38143558/39076597-76decdae-44b9-11e8-8118-138b681336de.png)

**Comment by aleqx** [comment]
@xmrig @CryptoMinerd Please just stop the bashing in here. This is definitely not the place to discuss your opinion about the coin, the dev team or trading. Use reddit, discord, etc for all that. Let's keep it xmrig miner software oriented in here.

It's disappointing that the xmrig dev has essentially encouraged this kind of attitude on Github.

p.s. The new IPBC algo is not heavy, it's a variant of cryptonight-lite with same hashrates as Turtle. Not sure where you got your opinions from ...

**Comment by CryptoMinerd** [comment]
It is not disappointing. He an I are simply stating observations.

Thanks for the heads up on the algorithm part though.

I will amend my previous statements. I misread https://github.com/ipbc-dev/ipbc-miner/commit/93fb121a19626e0c1b9dac9a0e2af73072be9fea

I had some how swapped the symbols in my head.

-constexpr size_t CRYPTONIGHT_IPBC_MEMORY = 4 * 1024 * 1024;
+constexpr size_t CRYPTONIGHT_IPBC_MEMORY = 1 * 1024 * 1024;

Cryptonight=2MB, Cryptonight-Light=1MB yep got it. Thinking you were doubling the 2 MB or perhaps I misspoke on purpose to bring attention to some issues noted not just from developer stand point. But a legal one.

I would hope to see IPBC implemented in @xmrig anyways but there is more to software than just the code... ;-)

"Special" means "new" and only they and SB miner something seems to have it implemented yet.

Try not to get all emotional...

**Comment by aleqx** [comment]
@CryptoMinerd You're new, I get it. It was your first post on Github. Your emotions and "observations" about a coin or its devs belong on reddit or 4chan, so please post them there. Github is meant for code and one should do some actual research before posting. Thank you.

**Comment by CryptoMinerd** [comment]
@aleqx Is this an ad for reddit, 4chan, or bitcointalk etc? New to you. Not to dev or to Github (I have other Github accounts) this is the first posting though to this new account. I know the rules for posting on threads. This one is specific to a request to support IPBC. I am keeping non-dev talk to a minimum.

Like I said there is more to software than just code. If I had violated any rules I am sure you would have pointed them out.

Nope. Call me Captain Obvious. For stating the obvious... ;-)

**Comment by aleqx** [comment]
> Is this an ad for reddit, 4chan, or bitcointalk etc?

No, it was a metric of the value and usefulness of your posts in here.

**Comment by CryptoMinerd** [comment]
@aleqx Fair enough... though it is certainly relevant to a discussion on IPBC support. Since I won't be developing the software to support IPBC. Though your tempting me to ask to do a pr... just so you can go back to reddit, 4chan, or bitcointalk IPBC subreddits or whatever.

> @xmrig Don't worry I will support IPBC sometime later, maybe after a week, I just say it not high priority. It will be added together with https://github.com/xmrig/xmrig-proxy/issues/168

**Comment by aleqx** [comment]
> it is certainly relevant to a discussion on IPBC support

No. Bashing devs and price on Github is not relevant to miner code implementation by any means.

You also don't need permission to do a PR. Best of luck.

**Comment by CryptoMinerd** [comment]
@aleqx After forking, opening the project, and running it. I looks like the thing that needs to change is how your miner handles nicehash. You know the nonce that is generated for each hash? That works differently in nicehash mode.

**Comment by aleqx** [comment]
> @aleqx After forking, opening the project, and running it. I looks like the thing that needs to change is how your miner handles nicehash. You know the nonce that is generated for each hash? That works differently in nicehash mode.

Not sure why you're addressing me.

**Comment by CryptoMinerd** [comment]
So you are saying that https://github.com/xmrig/xmrig needs to support the algorithm because the IPBC people won't add support for nicehash?

**Comment by CryptoMinerd** [comment]
@xmrig @aleqx I have merged the pull request https://github.com/ipbc-dev/ipbc-miner/pull/6 Thereby adding support for IPBC to xmrig-proxy. Now go back to your IPBC subreddit ... :-P

**Comment by ipbc-dev** [comment]
we tried to get in contact with various mining app devs before the fork and were ignored, so we decided to fork our own @xmrigs just being rude and thus unprofessional himself, rather than simply asking, he delivers such a show, we have no interest in working together since then.

this is also the end of the discussion for us, if our community wants something from us, we will deliver it in a separete repo.

**Comment by CryptoMinerd** [comment]
@aleqx +1 You know what you are right for trying to smooth things out. See there is more to software than just the code... ;-) (I consider it likely that all this has nothing to do with the people writing the code and more about the business side of things)

Ultimately, all devs here are giving freely of their code even if paid to do so and they benefit when others do the same. Community support is important for mineable currencies.

Communication between various mining projects helps the mining dev community and crypto as a whole.

So let this be the start of that official communication. IPBC wants their own algorithm and they want community support. @ipbc-dev should be providing most of the code to do it though.

Motivations differ though and what needs to be addressed directly is control.

@ipbc-dev +1 For getting the ball rolling when nobody is helping you get things done. (I trust when you say nobody was paying attention)

@xmrig @fireice-uk +1 Love your software man. Thanks! Keep rolling out the best. ;-)

@CryptoMinerd +1 for stirring up the muck and getting the ball rolling when our favorite mining software doesn't support IPBC.

@ipbc-dev Could you be so kind as to "support" your changes in the broader community?

What do I mean by "support"?

Part 1: It would really be helpful if you could properly fork:

https://github.com/xmrig/xmrig
https://github.com/fireice-uk/xmr-stak

Change the few dozen lines. Also if you could add support for Cuda for XMR stack. I don't program it so I don't want to run my mouth when I couldn't do it myself. But maybe you could see @psychocrypt could assist you.

Get @xmrig @fireice-uk to merge your pull requests into master to support IPBC and make it official.

@ipbc-dev You are still going to be getting paid to program even if it is on someone else's project and you currency will become more popular if for no other reason than it has its own algorithm and a platform it supports.

You can still create a separate project if you want to compete with @xmrig @fireice-uk but the algorithm support still needs to be there for the broader community and this type of special attention should require some support from @ipbc-dev.

Persistence pays off. Think of all those persistent miners out there... ;-)

Why should you play ball? Because it keeps people from having to react so quickly, hack around, or make you create your own little separate island projects while still making IPBC stand out with its own hashing algorithm and... and @xmrig @fireice-uk keeps getting those donations. Lulz

@ipbc-dev Part two... Raise the issue with the business side of things where you're at that your pool has become a monster. Ask if you set some of your rigs anonymously to different pools to spread the love and help prevent network attack.

Done. Whole issue resolved. IPBC keeps rising. 

Besides, if we can fix this issue then we can all leave our rigs mining IPBC for some time and go do something else. Then @aleqx can go back to reddit... (Lulz)

**Comment by ipbc-dev** [comment]
we have no troubles to handle this task and they are welcome, but we want also that others here understand that we are a very young project and new in crypto, this should be respected.

we have no troubles when other devs are teling us what we could do better and helping us to handle things better, but in a human friendly way and not starting a sh**show, stay professional.

For us, this topic is completed, we will start working on the task now.
