### ISSUE TITLE
Proxy doesn't forward miners login to pool?

### ISSUE THREAD

**Issue by cminatti** [xmrig/xmrig-proxy#188]
From my tests, the proxy is not forwarding the miner's logins to the pool. 
The pool sees only 1 miner with the login set on config.json
Is that the only way it works?
That makes it un useful to pay to miners, also to ban bad miners.

**Comment by TheBoroer** [comment]
That's the way it's supposed to work. I think it's meant for you to combine your hash power from multiple nodes to a pool that bans you for a couple hours if you're solving hashes too slowly (e.g. NiceHash). I think for your use-case you're better off running your own full blown pool instead of running this proxy.

**Comment by Andlar94** [comment]
Use Simple mode, not nicehash mode

**Comment by cminatti** [comment]
"mode": "simple".  Nothing change.

**Comment by DrStein99** [comment]
Hi - I checked around, maybe I missed it.  Could not find the page that explains.  Can someone tell me what  simple, nicehash, or any other mode is?

**Comment by TheBoroer** [comment]
This is the best description of simple mode i could find:
https://github.com/xmrig/xmrig-proxy/issues/118#issuecomment-375172833

**Comment by xmrig** [comment]
Proxy not forwarding the miner's logins in any mode it by design, also it not possible technically in nicehash mode. If you need fully transparent TCP proxy, you can use haproxy.
Thank you.
