### ISSUE TITLE
What is that

### ISSUE THREAD

**Issue by mk148a** [xmrig/xmrig-proxy#2]
Hi, sorry for this. I dont understand what does it do. Can you explain it for me please. Its proxy for xmr miner? I need aeon miner proxy

**Comment by mk148a** [comment]
Thanks for your answer, i am use xmrrig miner for aeon mining. I have firewall rules on my network its so hard rules. Only work 80 port, cant mine on 3333,4444,5555 and 8080 port. How can use this proxy for mining 80 port? I am aeon miner and i want use it for mine.aeon-pool.com:8080


xmrig-proxy.exe -o stratum+tcp://mine.aeon-pool.com:8080 -u Wmblablablamywallet -p x -b 0.0.0.0:80 -l log (i have server and i am opened this on my server 80 port is oppened but its not worked, i don't understand nicehash nonce option, i am not use nicehash only use mine.aeon-pool)

**Comment by xmrig** [comment]
You need run proxy somewhere outside your network. 

1. Setup proxy outside you network, If I understood you correctly, you already did it.
2. If address of your server is 1.2.3.4 (for example) point miner to `-o 1.2.3.4:80` and add `--nicehash` option.

But It can won't help you if traffic to 80 port wrapped to transparent HTTP proxy and it not just port restriction.

**Comment by mk148a** [comment]
Okay, its working on my local ip but its not work on wan ip, already my port forwarding options is opened.

**Comment by mk148a** [comment]
Its worked perfectly, i am close other 80 port service(word wide service) and its worked like charm! Thanks for coding it.
https://i.hizliresim.com/1g3a55.png

**Comment by xmrig** [comment]
Good, also I recommended use fixed diff on proxy `-u wallet+10000`, but if you use just one miner can leave it as is.

**Comment by djfinch** [comment]
Can I have one question? Some of my miners using xmrig (thank you for your awesome work BTW) but some of the other needs yam (they are all OSX - 8core MacPros - and i got better H/s with yam), unfortunately I'm not able to set up yam to successfully connect to proxy.
xmrig miner is fine, using just -o proxyIP:port and nothing else but yam needs stratum format, for example ... ./yam -M stratum+tcp://wallet:pass@pooladdress:port/xmr
above does not work. Still getting unable to connect/wrong pass and so. Not sure how to bring them to work... :(

PS: xmrig-2.2.0 compiled from source on Mac even Win64 binary work fine but after I quit (Ctrl+C) I can't see anything typed on my bash, previous commands, etc (they are not displaying but commands works). I must close terminal (tmux window for this connection) and connect once again...

**Comment by xmrig** [comment]
Proxy currently ignore wallet and pass so you can use any, yam miner connected successfully but it won't work with proxy because yam lack nicehash support, also for xmrig need add `--nicehash` option. Without this option, it is detected in 255 of 256 connections automatically.

Thank you I confirm bug with terminal, after exit I not property reset terminal, will fix it soon.

**Comment by djfinch** [comment]
Thank you for your quick answer. I was not clear enough. I'm using xmrig and yam only for monero so no nicehash support needed. I will test it after I came home. BTW my xmrig-proxy is running on Deb8, compiled from source, libuv1 needs to be "dpgk'ed" manually but everything works as expected. Logs looks fine and as I said - xmrig will connect successfully so there are probably something with yam (m8a). Just trying to simply/unify management of 12-15 standalone miners, all of them on OSX and tunneled from one digging machine using ssh port to debian server running proxy because they are all on private network. 

Also, thank you for upcoming terminal fix. You are awesome!

@mk148a - from your screenshot - wumpdate.exe ??? that's funny, really. :)

**Comment by xmrig** [comment]
Proxy use nicehash method to reduce connection count to pool in ideal case up to 256 miners in one pool connection. But it mean miner need support nicehash it just one byte difference in protocol but not all miners support it. It make proxy compatible with any pool and dramatically reduce pool load in large count of miners.

xmrig detects nicehash in most cases, but in one of 256 connections no way detect it because no difference in protocol, that byte is 0.

**Comment by xmrig** [comment]
Also you can try node.js proxy from `legacy` branch, it pretty simple, not reduce connection count, but comparable with any miner.

**Comment by djfinch** [comment]
Perfect. It's all new to me but this explains everything. Thank you once
again.

Kind regards,
Petr

2017-08-03 12:18 GMT+02:00 xmrig <notifications@github.com>:

**Comment by xmrig** [comment]
I make new release 2.2.1 with terminal fix. Proxy affected too I fix it only in source (dev branch).

**Comment by djfinch** [comment]
Terminal exit issue fixed as expected. Tested right now, OSX10.11.6,
compiled from source. Awesome work, thank you! Donations changed from
default to 10 ;)

2017-08-04 11:52 GMT+02:00 xmrig <notifications@github.com>:

**Comment by lexphor** [comment]
As far as I understand, the purpose of this program is to be the 'middle-man' between multiple miners and the pool. If that's true, and please pardon my noob-like question, then what exactly are the advantages of using this proxy program instead of just pointing multiple miners directly to the pool?

**Comment by snipeTR** [comment]
aga ne işe yarıyomuş allah için söyle mk148a
