### ISSUE TITLE
Please explain the principle of operation --custom-diff=N

### ISSUE THREAD

**Issue by sergneo** [xmrig/xmrig-proxy#47]
for example, in settings I set a fixed difficulty-u wallet.60000, then the --custom-diff=6000. This means that 10 the worker receives task complexity 6000 for one in 60000 ?

**Comment by xmrig** [comment]
Workers will receive 6000, but only 60000+ will be submitted to pool. Any worker can found hash with any diff (speed doesn't mater).

Examples:
Workers found share with actual diff 15000, worker submit it, but proxy will ignore it, because pool required 60000

100000 will be submitted on pool, because 100000 > 60000, but pool calculate it as 60000.

Actually custom diff on worker side only useful for miners without keepalve support to prevent timeouts.
Thank you.

**Comment by dorimanx** [comment]
I have seen that if i dont set custom diff on small 160hs machines, then proxy will give each miner 50k diff to search that i set on wallet.50000 then small miner will have a hard time finding share, and hash rate will be low, but when i send them 500diff and 50k to pool then 100 same miners getting hash rate of 10.5khs no problem and submit share of 50k every 2 to 3 sec to pool.  
So its not the best config? What i am missing? Large shares above 50k?

**Comment by velicumugur** [comment]
i have this setup: xmrig proxy + 3 rigs +1 upstream . each rig receive a 200k diff job. how can i set proxy to to send only one 200k job to this rigs?
