### ISSUE TITLE
The new version does not run on Ubuntu 23.10

### ISSUE THREAD

**Issue by masterjek** [xmrig/xmrig-proxy#560]
Hello. The new version does not run on the newest version of Ubuntu 23.10 You wrote that support for older versions of Ubuntu has been discontinued, but it turns out that support for the newest ones has also been discontinued?

**Comment by xmrig** [comment]
Please provide more information: what build you downloaded, because nothing changes if you build from the source.
Thank you.

**Comment by masterjek** [comment]
I downloaded this version - xmrig-proxy-6.21.1-linux-static-x64.tar.gz
The previous version that works without problems is - xmrig-proxy-6.21.0-linux-x64.tar.gz

**Comment by xmrig** [comment]
You can use [xmrig-proxy-6.21.1-jammy-x64.tar.gz](https://github.com/xmrig/xmrig-proxy/releases/download/v6.21.1/xmrig-proxy-6.21.1-jammy-x64.tar.gz) general rule: build for older Ubuntu works on newer versions.

`linux-static` was broken for a long time, it has been fixed in the dev branch now.
Thank you.
